### ISSUE TITLE
Nibble overwrites rfid without any validation

### ISSUE THREAD

**Issue by duvholt** [dotKom/nibble#10]
I had my rfid overwritten by my username + part of password + rfid this weekend. 
Erik Wiker also had his rfid overwritten with a leading space. 

I think the problem happens when a "faulty" rfid is scanned and the user tries to register. If successfully logged in whatever was written earlier is used as rfid. 

Either way there should be some checks to see if the input actually is an rfid.
Should be a number with length 10 (I think). 
Maybe strip whitespace too.

**Comment by arwassa** [comment]
Should be fixed, would appreciate feed back on it thought.

**Comment by sklirg** [comment]
Where was this fixed? Would be nice with some code to look at to do code review of the fix.

**Comment by arwassa** [comment]
Should be fixed.
11. feb. 2016 12:12 skrev "Håkon Solbjørg" notifications@github.com:

**Comment by sklirg** [comment]
If you want feedback on the fix I'd like to see the actual fix.

**Comment by arwassa** [comment]
Sorry about that. Was primarily thinking about feedback related to whether this was still a persisting issue, but if you could take a look on the code and give some feedback on it that would be great too. The code handling the login is in [views/login/login.js](https://github.com/dotKom/nibble/blob/master/views/login/login.js). and the part that caused the issue was the key logging I would assume.

**Comment by sklirg** [comment]
No problems. Will have a look in the morning.

**Comment by duvholt** [comment]
I don't see any input validation in login.js. 
The bug that caused this might be fixed, but I would really like to see some extra protection for this happening again. 

Something as simple as `rfid.match(/^\d{8,10}$/) !== null` should be enough. 

(I found one user with rfid length 8, but the rest is 10).

**Comment by nornes** [comment]
I spent some time Tuesday trying to figure out the length of rfid, and I found older cards have 8, whilst the newer have 10. The system used by Realfagskjelleren claims raid can be between 8-20, so we might want to include longer numbers in case NTNU expands the number again. Especially now with the infusion if all students from HIST and Gjøvik is going to get their own number as well.
