### ISSUE TITLE
Money modal number pad

### ISSUE THREAD

**Issue by Torrib** [dotKom/nibble#8]
The input fields for adding a custom amount of money should spawn a number pad instead of the full keyboard if possible.

**Comment by arwassa** [comment]
Fixed

**Comment by arwassa** [comment]
Windows is stupid :/
Not possible to get a pure numpad keyinput for number input fields.
Will need to have a look at other keyboard options, like js implemented keyboards or custom keyboards for windows.

**Comment by Torrib** [comment]
This isn't really that important.
I just assumed that changing the field to a number type would do this automatically.
